### ISSUE TITLE
Restrict what types of resource can be harvested by a unit

### ISSUE THREAD

**Issue by dusktreader** [zudijyr/Building-Sim-Game#20]
Right now, if you add an action to harvest any resource for a unit, it will try to harvest it. This means that a ship can chop wood....d'oh!

**Comment by zudijyr** [comment]
To some extent this will be solved by restricting their movement... as long as the ship can't get to the wood, it can't chop it, so no problem.
But yeah at some point there will be land units that can't harvest it either.  It's hard to say exactly how this will work since I don't have all the units planned out yet.  But one easy solution is to just have "can_harvest" flag for units like peasants to distinguish them from, say, a train.  And then it would just be binary for everything.. either they can or can't harvest.  We may need to fine tune it more later, but that should work for now.

**Comment by dusktreader** [comment]
This issue was solved by adding a set of 'harvestable_resources' to the Unit class. This should be populated at init time. See Peasant for the usage
